steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/boilerplate-repository/boilerplate-sapper:$COMMIT_SHA",
        ".",
      ]
  # push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/boilerplate-repository/boilerplate-sapper:$COMMIT_SHA",
      ]
  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "boilerplate-sapper"
      - "--image"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/boilerplate-repository/boilerplate-sapper:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/boilerplate-repository/boilerplate-sapper:$COMMIT_SHA"
